-- Update exercises with comprehensive muscle group data and other information
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Abs'] WHERE name = 'Ab Wheel Roll‑Out';
UPDATE exercises SET primary_muscles = ARRAY['Cardio', 'Full Body'] WHERE name = 'Air Bike Sprint';
UPDATE exercises SET primary_muscles = ARRAY['Shoulders', 'Chest'] WHERE name = 'Arnold Press';
UPDATE exercises SET primary_muscles = ARRAY['Lower Back', 'Glutes'] WHERE name = 'Back Extension';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Back Squat (High‑Bar)';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Back Squat (Low‑Bar)';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps', 'Shoulders'] WHERE name = 'Barbell Bench Press';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Middle Traps'] WHERE name = 'Barbell Bent‑Over Row';
UPDATE exercises SET primary_muscles = ARRAY['Biceps'] WHERE name = 'Barbell Curl';
UPDATE exercises SET primary_muscles = ARRAY['Cardio', 'Full Body'] WHERE name = 'Battle Rope Waves';
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Glutes'] WHERE name = 'Bird‑Dog';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes', 'Calves'] WHERE name = 'Box Jump';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Box Squat';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes', 'Calves'] WHERE name = 'Broad Jump';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Bulgarian Split Squat';
UPDATE exercises SET primary_muscles = ARRAY['Abs', 'Core'] WHERE name = 'Cable Crunch';
UPDATE exercises SET primary_muscles = ARRAY['Biceps'] WHERE name = 'Cable Curl';
UPDATE exercises SET primary_muscles = ARRAY['Glutes', 'Hamstrings'] WHERE name = 'Cable Pull‑Through';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Middle Traps'] WHERE name = 'Cable Seated Row';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Middle Traps'] WHERE name = 'Chest‑Supported Row';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Biceps'] WHERE name = 'Chin‑Up (Supinated)';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Olympic Lift'] WHERE name = 'Clean & Jerk';
UPDATE exercises SET primary_muscles = ARRAY['Triceps', 'Chest'] WHERE name = 'Close‑Grip Bench Press';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes', 'Lower Back'] WHERE name = 'Conventional Deadlift';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps'] WHERE name = 'Decline Bench Press';
UPDATE exercises SET primary_muscles = ARRAY['Triceps', 'Chest', 'Shoulders'] WHERE name = 'Dip (Parallel Bars)';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps', 'Shoulders'] WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET primary_muscles = ARRAY['Biceps'] WHERE name = 'Dumbbell Curl';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Middle Traps'] WHERE name = 'Dumbbell Row (Single‑Arm)';
UPDATE exercises SET primary_muscles = ARRAY['Rear Delts', 'Rhomboids'] WHERE name = 'Face Pull';
UPDATE exercises SET primary_muscles = ARRAY['Rear Delts', 'Rhomboids'] WHERE name = 'Face‑Pull (listed above)';
UPDATE exercises SET primary_muscles = ARRAY['Forearms', 'Core', 'Traps'] WHERE name = 'Farmer''s Carry';
UPDATE exercises SET primary_muscles = ARRAY['Front Delts', 'Shoulders'] WHERE name = 'Front Raise';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Core'] WHERE name = 'Front Squat';
UPDATE exercises SET primary_muscles = ARRAY['Glutes', 'Hamstrings'] WHERE name = 'Glute Bridge';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Goblet Squat';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes', 'Lower Back'] WHERE name = 'Good Morning';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Hack Squat (Machine)';
UPDATE exercises SET primary_muscles = ARRAY['Biceps', 'Forearms'] WHERE name = 'Hammer Curl';
UPDATE exercises SET primary_muscles = ARRAY['Abs', 'Hip Flexors'] WHERE name = 'Hanging Knee Raise';
UPDATE exercises SET primary_muscles = ARRAY['Abs', 'Hip Flexors'] WHERE name = 'Hanging Leg Raise';
UPDATE exercises SET primary_muscles = ARRAY['Glutes', 'Hamstrings'] WHERE name = 'Hip Thrust (Barbell)';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps', 'Shoulders'] WHERE name = 'Incline Dumbbell Bench Press';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Biceps'] WHERE name = 'Inverted Row';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes', 'Calves'] WHERE name = 'Jumping Squat';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Olympic Lift'] WHERE name = 'Kettlebell Clean';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Olympic Lift'] WHERE name = 'Kettlebell Snatch';
UPDATE exercises SET primary_muscles = ARRAY['Glutes', 'Hamstrings', 'Core'] WHERE name = 'Kettlebell Swing';
UPDATE exercises SET primary_muscles = ARRAY['Shoulders', 'Core'] WHERE name = 'Landmine Press';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Biceps'] WHERE name = 'Lat Pull‑Down';
UPDATE exercises SET primary_muscles = ARRAY['Side Delts', 'Shoulders'] WHERE name = 'Lateral Raise';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Leg Press';
UPDATE exercises SET primary_muscles = ARRAY['Shoulders', 'Triceps'] WHERE name = 'Machine Shoulder Press';
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Full Body'] WHERE name = 'Medicine Ball Slam';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Chest', 'Triceps'] WHERE name = 'Muscle‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Neck'] WHERE name = 'Neck Extension (Plate)';
UPDATE exercises SET primary_muscles = ARRAY['Neck'] WHERE name = 'Neck Flexion (Plate)';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Biceps'] WHERE name = 'Neutral‑Grip Pull‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes'] WHERE name = 'Nordic Ham Curl';
UPDATE exercises SET primary_muscles = ARRAY['Shoulders', 'Triceps'] WHERE name = 'Overhead Barbell Press';
UPDATE exercises SET primary_muscles = ARRAY['Triceps'] WHERE name = 'Overhead Triceps Extension';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes', 'Core'] WHERE name = 'Pistol Squat';
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Abs'] WHERE name = 'Plank';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Olympic Lift'] WHERE name = 'Power Clean';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Olympic Lift'] WHERE name = 'Power Snatch';
UPDATE exercises SET primary_muscles = ARRAY['Biceps'] WHERE name = 'Preacher Curl';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Biceps'] WHERE name = 'Pull‑Up (Pronated)';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps', 'Shoulders'] WHERE name = 'Push‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Rear Delts', 'Rhomboids'] WHERE name = 'Rear Delt Fly';
UPDATE exercises SET primary_muscles = ARRAY['Biceps', 'Forearms'] WHERE name = 'Reverse Curl';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Reverse Lunge';
UPDATE exercises SET primary_muscles = ARRAY['Forearms'] WHERE name = 'Reverse Wrist Curl';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes'] WHERE name = 'Romanian Deadlift';
UPDATE exercises SET primary_muscles = ARRAY['Cardio', 'Full Body'] WHERE name = 'Rower Erg Sprint';
UPDATE exercises SET primary_muscles = ARRAY['Abs', 'Core'] WHERE name = 'Russian Twist';
UPDATE exercises SET primary_muscles = ARRAY['Calves'] WHERE name = 'Seated Calf Raise';
UPDATE exercises SET primary_muscles = ARRAY['Shoulders', 'Triceps'] WHERE name = 'Seated Dumbbell Shoulder Press';
UPDATE exercises SET primary_muscles = ARRAY['Traps', 'Shoulders'] WHERE name = 'Shrug (Barbell)';
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Obliques'] WHERE name = 'Side Plank';
UPDATE exercises SET primary_muscles = ARRAY['Glutes', 'Hamstrings'] WHERE name = 'Single‑Leg Glute Bridge';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps'] WHERE name = 'Sissy Squat';
UPDATE exercises SET primary_muscles = ARRAY['Triceps'] WHERE name = 'Skull Crusher';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Cardio'] WHERE name = 'Sled Pull (Backward)';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes', 'Cardio'] WHERE name = 'Sled Push';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Split Squat (Static)';
UPDATE exercises SET primary_muscles = ARRAY['Calves'] WHERE name = 'Standing Calf Raise';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Step‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes'] WHERE name = 'Stiff‑Leg Deadlift';
UPDATE exercises SET primary_muscles = ARRAY['Core', 'Forearms'] WHERE name = 'Suitcase Carry';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes', 'Quadriceps'] WHERE name = 'Sumo Deadlift';
UPDATE exercises SET primary_muscles = ARRAY['Lats', 'Rhomboids', 'Middle Traps'] WHERE name = 'T‑Bar Row';
UPDATE exercises SET primary_muscles = ARRAY['Tibialis Anterior'] WHERE name = 'Tibialis Raise';
UPDATE exercises SET primary_muscles = ARRAY['Hamstrings', 'Glutes', 'Quadriceps'] WHERE name = 'Trap‑Bar Deadlift';
UPDATE exercises SET primary_muscles = ARRAY['Triceps'] WHERE name = 'Triceps Rope Push‑Down';
UPDATE exercises SET primary_muscles = ARRAY['Full Body', 'Core'] WHERE name = 'Turkish Get‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Walking Lunge';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Shoulders', 'Core'] WHERE name = 'Wall Ball';
UPDATE exercises SET primary_muscles = ARRAY['Quadriceps', 'Glutes'] WHERE name = 'Wall Sit';
UPDATE exercises SET primary_muscles = ARRAY['Chest', 'Triceps', 'Shoulders'] WHERE name = 'Weighted Push‑Up';
UPDATE exercises SET primary_muscles = ARRAY['Forearms'] WHERE name = 'Wrist Curl';