
-- =========================================================
-- 1. TABLES (dependency order)
-- =========================================================

CREATE TABLE public.exercise_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE public.exercises (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer REFERENCES public.exercise_categories(id) ON DELETE SET NULL,
    name text NOT NULL,
    primary_muscles text[],
    gif_url text
);

CREATE TABLE public.users (
    id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    username text,
    email text,
    goal text,
    experience text,
    injuries text[],
    equipment text[],
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.programs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    days_per_week integer,
    generator_source text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.workouts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id uuid REFERENCES public.programs(id) ON DELETE CASCADE,
    workout_date date,
    json_plan jsonb,
    completed boolean DEFAULT false
);

CREATE TABLE public.workout_exercises (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workout_id uuid REFERENCES public.workouts(id) ON DELETE CASCADE,
    exercise_id integer REFERENCES public.exercises(id) ON DELETE SET NULL,
    "position" integer
);

CREATE TABLE public.sets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workout_exercise_id uuid REFERENCES public.workout_exercises(id) ON DELETE CASCADE,
    reps integer,
    weight numeric(6,2),
    rir integer,
    performed_at timestamptz DEFAULT now()
);

CREATE TABLE public.ratings (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    exercise_id integer NOT NULL REFERENCES public.exercises(id) ON DELETE CASCADE,
    pump_score integer,
    notes text,
    updated_at timestamptz DEFAULT now(),
    manual_1rm numeric,
    manual_1rm_updated_at timestamptz,
    PRIMARY KEY (user_id, exercise_id),
    CONSTRAINT ratings_pump_score_check CHECK (pump_score >= 1 AND pump_score <= 5)
);

CREATE TABLE public.conversation_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    conversation_data jsonb DEFAULT '[]'::jsonb,
    analytics_cache jsonb,
    insights text[] DEFAULT ARRAY[]::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.performance_metrics (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id text,
    metric_type text NOT NULL,
    value numeric NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    "timestamp" timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- =========================================================
-- 2. GRANTS
-- =========================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercise_categories TO authenticated;
GRANT ALL ON public.exercise_categories TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercises TO authenticated;
GRANT ALL ON public.exercises TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT ALL ON public.users TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.programs TO authenticated;
GRANT ALL ON public.programs TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.workouts TO authenticated;
GRANT ALL ON public.workouts TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.workout_exercises TO authenticated;
GRANT ALL ON public.workout_exercises TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sets TO authenticated;
GRANT ALL ON public.sets TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ratings TO authenticated;
GRANT ALL ON public.ratings TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversation_sessions TO authenticated;
GRANT ALL ON public.conversation_sessions TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.performance_metrics TO authenticated;
GRANT ALL ON public.performance_metrics TO service_role;

-- =========================================================
-- 3. RLS
-- =========================================================

ALTER TABLE public.exercise_categories   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programs              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_exercises     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sets                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_metrics   ENABLE ROW LEVEL SECURITY;

-- Public catalog (authenticated read)
CREATE POLICY "Everyone can view exercise categories"
  ON public.exercise_categories FOR SELECT TO authenticated USING (true);

CREATE POLICY "Everyone can view exercises"
  ON public.exercises FOR SELECT TO authenticated USING (true);

-- users
CREATE POLICY "Users can view their own profile"
  ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile"
  ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile"
  ON public.users FOR UPDATE USING (auth.uid() = id);

-- programs
CREATE POLICY "Users can view their own programs"
  ON public.programs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own programs"
  ON public.programs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own programs"
  ON public.programs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own programs"
  ON public.programs FOR DELETE USING (auth.uid() = user_id);

-- workouts
CREATE POLICY "Users can view their own workouts"
  ON public.workouts FOR SELECT
  USING (auth.uid() = (SELECT user_id FROM public.programs WHERE id = program_id));
CREATE POLICY "Users can create their own workouts"
  ON public.workouts FOR INSERT
  WITH CHECK (auth.uid() = (SELECT user_id FROM public.programs WHERE id = program_id));
CREATE POLICY "Users can update their own workouts"
  ON public.workouts FOR UPDATE
  USING (auth.uid() = (SELECT user_id FROM public.programs WHERE id = program_id));
CREATE POLICY "Users can delete their own workouts"
  ON public.workouts FOR DELETE
  USING (auth.uid() = (SELECT user_id FROM public.programs WHERE id = program_id));

-- workout_exercises
CREATE POLICY "Users can view their own workout exercises"
  ON public.workout_exercises FOR SELECT
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    WHERE w.id = workout_id));
CREATE POLICY "Users can create their own workout exercises"
  ON public.workout_exercises FOR INSERT
  WITH CHECK (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    WHERE w.id = workout_id));
CREATE POLICY "Users can update their own workout exercises"
  ON public.workout_exercises FOR UPDATE
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    WHERE w.id = workout_id));
CREATE POLICY "Users can delete their own workout exercises"
  ON public.workout_exercises FOR DELETE
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    WHERE w.id = workout_id));

-- sets
CREATE POLICY "Users can view their own sets"
  ON public.sets FOR SELECT
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    JOIN public.workout_exercises we ON w.id = we.workout_id
    WHERE we.id = workout_exercise_id));
CREATE POLICY "Users can create their own sets"
  ON public.sets FOR INSERT
  WITH CHECK (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    JOIN public.workout_exercises we ON w.id = we.workout_id
    WHERE we.id = workout_exercise_id));
CREATE POLICY "Users can update their own sets"
  ON public.sets FOR UPDATE
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    JOIN public.workout_exercises we ON w.id = we.workout_id
    WHERE we.id = workout_exercise_id));
CREATE POLICY "Users can delete their own sets"
  ON public.sets FOR DELETE
  USING (auth.uid() = (
    SELECT p.user_id FROM public.programs p
    JOIN public.workouts w ON p.id = w.program_id
    JOIN public.workout_exercises we ON w.id = we.workout_id
    WHERE we.id = workout_exercise_id));

-- ratings
CREATE POLICY "Users can view their own ratings"
  ON public.ratings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own ratings"
  ON public.ratings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own ratings"
  ON public.ratings FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own ratings"
  ON public.ratings FOR DELETE USING (auth.uid() = user_id);

-- conversation_sessions
CREATE POLICY "Users can view their own conversation sessions"
  ON public.conversation_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own conversation sessions"
  ON public.conversation_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own conversation sessions"
  ON public.conversation_sessions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own conversation sessions"
  ON public.conversation_sessions FOR DELETE USING (auth.uid() = user_id);

-- performance_metrics
CREATE POLICY "Users can view their own performance metrics"
  ON public.performance_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own performance metrics"
  ON public.performance_metrics FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =========================================================
-- 4. FUNCTIONS, TRIGGERS, VIEWS
-- =========================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_conversation_sessions_updated_at
BEFORE UPDATE ON public.conversation_sessions
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Progress view
CREATE VIEW public.v_progress AS
SELECT s.id, s.workout_exercise_id, s.weight, s.reps, s.rir, s.performed_at,
       w.workout_date, we.exercise_id, e.name AS exercise_name, p.user_id,
       (s.weight * s.reps::numeric) AS volume,
       CASE WHEN s.reps > 0 AND s.weight > 0
            THEN s.weight * (1::numeric + ((s.reps + COALESCE(s.rir,0))::numeric / 30.0))
            ELSE NULL END AS estimated_1rm
FROM public.sets s
JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
JOIN public.workouts w ON we.workout_id = w.id
JOIN public.programs p ON w.program_id = p.id
JOIN public.exercises e ON we.exercise_id = e.id
WHERE w.completed = true;

-- Core lifts view
CREATE VIEW public.v_core_lifts AS
SELECT id, name,
  CASE
    WHEN lower(name) LIKE '%squat%' AND lower(name) NOT LIKE '%front%' THEN 'squat'
    WHEN lower(name) LIKE '%bench%' AND lower(name) NOT LIKE '%incline%' THEN 'bench'
    WHEN lower(name) LIKE '%deadlift%' THEN 'deadlift'
    WHEN lower(name) LIKE '%overhead press%' OR lower(name) LIKE '%military press%'
      OR (lower(name) LIKE '%press%' AND lower(name) LIKE '%standing%') THEN 'overhead_press'
    ELSE NULL
  END AS core_lift_type
FROM public.exercises
WHERE lower(name) LIKE '%squat%' OR lower(name) LIKE '%bench%' OR lower(name) LIKE '%deadlift%'
   OR lower(name) LIKE '%overhead press%' OR lower(name) LIKE '%military press%'
   OR (lower(name) LIKE '%press%' AND lower(name) LIKE '%standing%');

-- Helper functions (all SECURITY DEFINER with locked search_path)

CREATE OR REPLACE FUNCTION public.get_user_history(p_user uuid)
RETURNS TABLE(exercise_name text, total_sets bigint, avg_weight numeric, avg_reps numeric, last_performed timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT e.name, COUNT(s.id), AVG(s.weight), AVG(s.reps), MAX(s.performed_at)
  FROM public.exercises e
  JOIN public.workout_exercises we ON e.id = we.exercise_id
  JOIN public.sets s ON we.id = s.workout_exercise_id
  JOIN public.workouts w ON we.workout_id = w.id
  JOIN public.programs p ON w.program_id = p.id
  WHERE p.user_id = p_user
  GROUP BY e.id, e.name
  ORDER BY MAX(s.performed_at) DESC
  LIMIT 50;
$$;

CREATE OR REPLACE FUNCTION public.get_user_progress(p_user_id uuid DEFAULT auth.uid())
RETURNS TABLE(user_id uuid, exercise text, week timestamptz, avg_weight numeric, avg_reps numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT p.user_id, e.name, date_trunc('week', s.performed_at), AVG(s.weight), AVG(s.reps)
  FROM public.sets s
  JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
  JOIN public.workouts w ON we.workout_id = w.id
  JOIN public.programs p ON w.program_id = p.id
  JOIN public.exercises e ON we.exercise_id = e.id
  WHERE p.user_id = p_user_id
  GROUP BY p.user_id, e.name, date_trunc('week', s.performed_at)
  ORDER BY date_trunc('week', s.performed_at) DESC;
$$;

CREATE OR REPLACE FUNCTION public.get_exercise_history(p_user_id uuid, p_exercise_id integer, p_limit integer DEFAULT 10)
RETURNS TABLE(weight numeric, reps integer, rir integer, performed_at timestamptz, max_weight numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT s.weight, s.reps, s.rir, s.performed_at,
         MAX(s.weight) OVER (PARTITION BY we.exercise_id) AS max_weight
  FROM public.sets s
  JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
  JOIN public.workouts w ON we.workout_id = w.id
  JOIN public.programs p ON w.program_id = p.id
  WHERE p.user_id = p_user_id AND we.exercise_id = p_exercise_id
  ORDER BY s.performed_at DESC
  LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION public.get_exercise_1rm_data(p_user_id uuid, p_exercise_id integer)
RETURNS TABLE(weight numeric, reps integer, rir integer, performed_at timestamptz, estimated_1rm numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT s.weight, s.reps, s.rir, s.performed_at,
         CASE WHEN s.reps > 0 AND s.weight > 0
              THEN s.weight * (1::numeric + ((s.reps + COALESCE(s.rir,0))::numeric / 30.0))
              ELSE NULL END
  FROM public.sets s
  JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
  JOIN public.workouts w ON we.workout_id = w.id
  JOIN public.programs p ON w.program_id = p.id
  WHERE p.user_id = p_user_id AND we.exercise_id = p_exercise_id
  ORDER BY s.performed_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.get_exercise_stats(p_user_id uuid, p_exercise_id integer)
RETURNS TABLE(exercise_id integer, exercise_name text, manual_1rm numeric, manual_1rm_updated_at timestamptz,
              calculated_1rm numeric, best_1rm numeric, total_sets bigint, avg_weight numeric, avg_reps numeric,
              last_performed timestamptz, pump_score integer, notes text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH set_data AS (
    SELECT s.weight, s.reps, s.rir, s.performed_at,
      CASE WHEN s.reps > 0 AND s.weight > 0
           THEN s.weight * (1::numeric + ((s.reps + COALESCE(s.rir,0))::numeric / 30.0))
           ELSE NULL END AS est_1rm
    FROM public.sets s
    JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
    JOIN public.workouts w ON we.workout_id = w.id
    JOIN public.programs p ON w.program_id = p.id
    WHERE p.user_id = p_user_id AND we.exercise_id = p_exercise_id
  )
  SELECT e.id, e.name, r.manual_1rm, r.manual_1rm_updated_at,
         (SELECT est_1rm FROM set_data ORDER BY performed_at DESC LIMIT 1),
         (SELECT MAX(est_1rm) FROM set_data),
         (SELECT COUNT(*) FROM set_data),
         (SELECT AVG(weight) FROM set_data),
         (SELECT AVG(reps) FROM set_data),
         (SELECT MAX(performed_at) FROM set_data),
         r.pump_score, r.notes
  FROM public.exercises e
  LEFT JOIN public.ratings r ON r.exercise_id = e.id AND r.user_id = p_user_id
  WHERE e.id = p_exercise_id;
$$;

CREATE OR REPLACE FUNCTION public.get_core_lift_progression(p_user_id uuid DEFAULT auth.uid())
RETURNS TABLE(core_lift_type text, exercise_name text, workout_date date, best_estimated_1rm numeric,
              total_volume numeric, avg_weight numeric, total_sets bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT cl.core_lift_type, e.name, w.workout_date,
         MAX(CASE WHEN s.reps > 0 AND s.weight > 0
                  THEN s.weight * (1::numeric + ((s.reps + COALESCE(s.rir,0))::numeric / 30.0)) END),
         SUM(s.weight * s.reps),
         AVG(s.weight),
         COUNT(s.id)
  FROM public.sets s
  JOIN public.workout_exercises we ON s.workout_exercise_id = we.id
  JOIN public.workouts w ON we.workout_id = w.id
  JOIN public.programs p ON w.program_id = p.id
  JOIN public.exercises e ON we.exercise_id = e.id
  JOIN public.v_core_lifts cl ON cl.id = e.id
  WHERE p.user_id = p_user_id AND cl.core_lift_type IS NOT NULL AND w.completed = true
  GROUP BY cl.core_lift_type, e.name, w.workout_date
  ORDER BY w.workout_date DESC;
$$;

CREATE OR REPLACE FUNCTION public.get_current_core_lift_maxes(p_user_id uuid DEFAULT auth.uid())
RETURNS TABLE(core_lift_type text, exercise_name text, current_1rm numeric, last_performed date, improvement_30d numeric)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH prog AS (
    SELECT * FROM public.get_core_lift_progression(p_user_id)
  )
  SELECT core_lift_type,
         (SELECT exercise_name FROM prog p2 WHERE p2.core_lift_type = p.core_lift_type ORDER BY workout_date DESC LIMIT 1),
         MAX(best_estimated_1rm) FILTER (WHERE workout_date = (SELECT MAX(workout_date) FROM prog p3 WHERE p3.core_lift_type = p.core_lift_type)),
         MAX(workout_date),
         MAX(best_estimated_1rm) FILTER (WHERE workout_date >= (CURRENT_DATE - INTERVAL '30 days'))
         - MAX(best_estimated_1rm) FILTER (WHERE workout_date < (CURRENT_DATE - INTERVAL '30 days'))
  FROM prog p
  GROUP BY core_lift_type;
$$;

CREATE OR REPLACE FUNCTION public.get_workout_frequency_stats(p_user_id uuid DEFAULT auth.uid())
RETURNS TABLE(total_workouts bigint, avg_workouts_per_week numeric, current_streak integer, longest_streak integer, last_workout_date date)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_total bigint;
  v_last date;
  v_first date;
  v_weeks numeric;
BEGIN
  SELECT COUNT(*), MAX(w.workout_date), MIN(w.workout_date)
    INTO v_total, v_last, v_first
  FROM public.workouts w
  JOIN public.programs p ON w.program_id = p.id
  WHERE p.user_id = p_user_id AND w.completed = true;

  v_weeks := GREATEST(1, EXTRACT(EPOCH FROM (COALESCE(v_last, CURRENT_DATE) - COALESCE(v_first, CURRENT_DATE)))/604800.0);
  RETURN QUERY SELECT v_total, ROUND(v_total::numeric / v_weeks, 2), 0, 0, v_last;
END;
$$;

CREATE OR REPLACE FUNCTION public.analyze_progress()
RETURNS json
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT json_build_object('generated_at', now());
$$;
