// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrydtdiphpjacqronemd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yeWR0ZGlwaHBqYWNxcm9uZW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzEzOTAsImV4cCI6MjA3MDAwNzM5MH0.WrRF88lKPnXZozm0xLRXN_DLntg3yk65V-KSgRVaiJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});